# Dependencies
markdown:         kramdown
highlighter:      pygments
plugins:
  - jekyll-gist
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Jorge Ramírez-Ruiz
tagline:          'A Jekyll theme'
description:      'PhD candidate at <a href="http://upf.edu" target="_blank">Universitat Pompeu Fabra</a>'
url:              http://jorgeerrz.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jorgeerrz/jorgeerrz.github.io
