# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jorge Ramírez-Ruiz
tagline:          'A Jekyll theme'
description:      'PhD candidate at [Universitat Pompeu Fabra](https://www.upf.edu)'
url:              http://jorgeerrz.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jorgeerrz/jorgeerrz.github.io
